require("lsp.servers.clangd")
require("lsp.servers.lua")
require("lsp.servers.tailwindcss")
require("lsp.servers.json")
-- require("lsp.servers.typescript")
require("lsp.servers.prisma")
require("lsp.servers.rust")
-- require("lsp.servers.java")
require("lsp.servers.kotlin")
require("lsp.servers.other")
